version: 2
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
        name: The First Step
        command: |
          echo 'Hello World!'
          echo 'This is the delivery pipeline'
      - run:
        name: Code has arrived
        command: |
          ls -al
          echo '^^^That should look familiar^^^'
      # - codecov/upload:
      #     file: {{ ../coverage/ }}

# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
#   codecov: codecov/codecov@1.0.2
# workflows:
#   node-tests:
#     jobs:
#       - node/test
