version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      # - codecov/upload:
      #     file: {{ ../coverage/ }}

# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
#   codecov: codecov/codecov@1.0.2
# workflows:
#   node-tests:
#     jobs:
#       - node/test
